builds:
  - binary: ngtools
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: ngtools
    homepage: https://github.com/waldirborbajr/ngtools
    tap:
      owner: waldirborbajr
      name: homebrew-waldirborbajr
    commit_author:
      name: waldirborbajr
      email: wborbajr@gmail.com

checksum:
  name_template: "checksums.txt"
