FROM golang:1.19 as build

ARG version=master

RUN git clone https://github.com/waldirborbajr/ngtools.git $GOPATH/src/github.com/waldirborbajr/ngtools && \
    cd $GOPATH/src/github.com/waldirborbajr/ngtools && \
    git checkout $version

ENV GOPROXY=https://proxy.golang.org,direct
ENV GO111MODULE=on
ENV GOSUMDB=off

WORKDIR $GOPATH/src/github.com/waldirborbajr/ngtools

ENV PATH=$PATH:./bin

RUN make build && \
    cp bin/ngtools /usr/local/bin/
